config/routes.rb
Rails.application.routes.draw do
  resources :clocks

  resources :settings

  get 'home/index' => 'home#index'
  get 'home/flot' => 'home#flot'
  get 'home/morris' => 'home#morris'
  get 'home/tables' => 'home#tables'
  get 'home/forms' => 'home#forms'

  get 'home/panels_wells' => 'home#panels_wells'
  get 'home/buttons' => 'home#buttons'
  get 'home/notifications' => 'home#notifications'
  get 'home/typography' => 'home#typography'
  get 'home/grid' => 'home#grid'
  get 'home/blank' => 'home#blank'
  get 'home/login' => 'home#login'

  root 'clocks#new'

end

app/models/clock.rb
#encoding: UTF-8
class Clock < ActiveRecord::Base
  validates_presence_of  :action
  validates_presence_of  :date
  validates_presence_of  :time
  validates_presence_of  :ip
  validates_presence_of  :user

  attr_accessor :pin

  validate :check_time_and_status
  validate :check_ip
  validates_length_of :message, minimum: 10, allow_nil: true, allow_blank: true, message: "Verificare la motivazione (troppo corta)"

  def check_ip
    last_check_in=Clock.where(date: self.date, ip: self.ip).first
    if last_check_in.nil?
      return true
    elsif last_check_in.user == self.user
      return true
    elsif  message.blank?
      self.errors.add(:base, "Questo indirizzo IP risulta già utilizzato da #{last_check_in.user}. E' necessario specificare una motivazione")
      return false
    end
  end

  def  check_time_and_status
    last_check_in=Clock.where(user: self.user, date: self.date, action: "check_in").first
    last_check_out=Clock.where(user: self.user, date: self.date, action: "check_out").first
    if action=="check_in" && last_check_in
      self.errors.add(:base, "L'utente ha gia effettuato il check in alle #{last_check_in.time}")
      return false
    end
    if action=="check_out" && last_check_out
      self.errors.add(:base, "L'utente ha gia effettuato il check out alle #{last_check_out.time}")
      return false
    end

    if Setting.where(group: "user_name",key: self.pin, value: self.user).first.nil?
      self.errors.add(:base, "il pin non è corretto")
      return false
    end

    delta = (Time.now - self.time).to_i / 60
    if delta.abs > 6 && message.blank?
      self.errors.add(:base, "Differenza #{delta} minuti - Per differenze maggiori di 5 minuti è necessario indicare una motivazione")
      return false
    end

  end

  def to_s
    "#{self.user} ha effettuato #{self.action} alle ore #{self.time.to_s} - Note: #{self.message}"
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  scope :active, -> {where(status: ["active", nil])}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :check_administrative_ip
  def check_administrative_ip
    redirect_to new_clock_url unless ADMINISTRATIVE_IPS.include? request.remote_ip
    return false
  end

  ADMINISTRATIVE_IPS = ["127.0.0.1","10.103.142.168","10.103.171.191", "10.64.5.144"]
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  before_action :set_clock, only: [:show, :edit, :update, :destroy]
  before_filter :check_administrative_ip, except: [:new, :create]
  # GET /clocks
  # GET /clocks.json
  def index

    @clocks = Clock.all
  end

  # GET /clocks/1
  # GET /clocks/1.json
  def show
    redirect_to new_clock_url
  end

  # GET /clocks/new
  def new
    @preset_ip=Setting.where(group: "ips", key: request.remote_ip).first
    @moment=Time.now.at_beginning_of_minute
    if @preset_ip.nil?
      @clock = Clock.new()
    else
      @clock = Clock.new(user: @preset_ip.value)
     end
  end

  # GET /clocks/1/edit
  #def edit
  #end

  # POST /clocks
  # POST /clocks.json
  def create
    clock_params[:message].strip!
    @clock = Clock.new(clock_params)
    @clock.date=Date.today
    @clock.time=Time.parse("#{params[:date][:hour]}:#{params[:date][:minute]}:00", @clock.date)
    @clock.ip=request.remote_ip
    @clock.pin=params[:pin]
    @moment=@clock.time.localtime # Time.now.at_beginning_of_minute
    #@moment=@moment.advance(minutes: -(@moment.min % 5))
    respond_to do |format|
      if @clock.save
        AdminMailer.timesheet(Date.today).deliver
        format.html { redirect_to new_clock_url, notice: "Registrazione #{@clock.action} per #{@clock.user} alle #{@clock.time} avvenuta con successo." }
        format.json { render :show, status: :created, location: @clock }
      else
        format.html { render :new }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocks/1
  # PATCH/PUT /clocks/1.json
  def update

    respond_to do |format|
      if @clock.update(clock_params)
        format.html { redirect_to @clock, notice: 'Clock was successfully updated.' }
        format.json { render :show, status: :ok, location: @clock }
      else
        format.html { render :edit }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocks/1
  # DELETE /clocks/1.json
  def destroy
    @clock.destroy
    respond_to do |format|
      format.html { redirect_to clocks_url, notice: 'Clock was successfully destroyed.' }
      format.json { head :no_content }
    end
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock
      @clock = Clock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clock_params
      params.require(:clock).permit(:date, :time, :user, :ip, :action, :message)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def blank

  end
  def index

  end
  def login
    render layout: "login"
  end
  def flot

  end
  def morris

  end
  def tables

  end
  def panels_wells

  end
  def buttons

  end
  def typography

  end
  def grid

  end
  def forms

  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:group, :key, :value, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def users_for_options
    Setting.active.where(group: "user_name").map{|x| [x.value]}.sort
  end
  def ips_for_hash
    Setting.active.where(group: "ips").inject(Hash.new()) { |memo,current | memo[current.value]=current.label; memo }
  end
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/clocks/_form.html.haml
= form_for @clock , role: "form" do |f|
  - if @clock.errors.any?
    .row.well-sm
      %span.col-xs-12
        #error_explanation
          - @clock.errors.full_messages.each do |msg|
            %h3.bg-danger.well-sm= msg
  .row.well-sm
    %span.col-xs-12
      =f.select :user, options_for_select(users_for_options, @clock.user) ,{include_blank: true}, class: "form-control block"
  .row.well-sm
    %span.col-xs-12
      =password_field_tag :pin, "", class: "form-control block" , placeholder:"insert pin here"
      -#=f.text_field :ip
      =f.hidden_field :action, id: "op"
  .row.well-sm
    %span.col-xs-6.col-md-6
      =select_hour(@moment,{ start_hour: 7, end_hour: 24}, {class: "btn btn-lg btn-default btn-block"})
    %span.col-xs-6.col-md-6
      =select_minute(@moment, {minute_step: 1}, {class: "btn btn-lg btn-default btn-block"})

    -#%span.col-xs-2
      -#%button.btn.btn-xs.btn-default.btn-block{:type => "button"} +
      -#%button.btn.btn-xs.btn-default.btn-block{:type => "button"} -
  .row.well-sm
    %span.col-xs-6
      %button.btn.btn-lg.btn-success.btn-block{id: "entrata", :type => "button"} Entrata
    %span.col-xs-6
      %button.btn.btn-lg.btn-danger.btn-block{id: "uscita",:type => "button"} Uscita
  .row.well-sm
    %span.col-xs-12
      %label.col-xs-2.control-label Annotazioni
      = f.text_area :message, class: "form-control block",  :rows => "3"
-if flash[:notice]
  %h3.bg-success.well-sm= flash[:notice]


:javascript
    $(document).ready( function() {
      $('#entrata').click(function()
        {$("#op").val("check_in");
        $("#new_clock").submit();})
      $('#uscita').click(function()
          {$("#op").val("check_out");
          $("#new_clock").submit();})
    } );

app/views/clocks/edit.html.haml
%h1 Editing clock

= render 'form'

= link_to 'Show', @clock
\|
= link_to 'Back', clocks_path

app/views/clocks/index.html.haml
%h1 Listing clocks

%table.table.table-striped
  %tr
    %th Created
    %th Date
    %th Time
    %th User
    %th Ip
    %th Action
    %th Message
    %th
    %th
    %th

  - @clocks.each do |clock|
    %tr
      %td= clock.created_at.localtime
      %td= clock.date
      %td= clock.time.localtime
      %td= clock.user
      %td= clock.ip
      %td= clock.action
      %td= clock.message
      %td= link_to 'Destroy', clock, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/clocks/new.html.haml
= render 'form'

app/views/clocks/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @clock.date
%p
  %b Time:
  = @clock.time
%p
  %b User:
  = @clock.user
%p
  %b Ip:
  = @clock.ip
%p
  %b Action:
  = @clock.action
%p
  %b Message:
  = @clock.message

= link_to 'Edit', edit_clock_path(@clock)
\|
= link_to 'Back', clocks_path

app/views/home/_dropdown_alerts.haml
%li
  %a{:href => "#"}
    %div
      %i.fa.fa-comment.fa-fw
      New Comment
      %span.pull-right.text-muted.small 4 minutes ago
%li.divider
%li
  %a{:href => "#"}
    %div
      %i.fa.fa-twitter.fa-fw
      3 New Followers
      %span.pull-right.text-muted.small 12 minutes ago
%li.divider
%li
  %a{:href => "#"}
    %div
      %i.fa.fa-envelope.fa-fw
      Message Sent
      %span.pull-right.text-muted.small 4 minutes ago
%li.divider
%li
  %a{:href => "#"}
    %div
      %i.fa.fa-tasks.fa-fw
      New Task
      %span.pull-right.text-muted.small 4 minutes ago
%li.divider
%li
  %a{:href => "#"}
    %div
      %i.fa.fa-upload.fa-fw
      Server Rebooted
      %span.pull-right.text-muted.small 4 minutes ago
%li.divider
%li
  %a.text-center{:href => "#"}
    %strong See All Alerts
    %i.fa.fa-angle-right
/ /.dropdown-alerts

app/views/home/_dropdown_messages.haml
%li
  %a{:href => "#"}
    %div
      %strong John Smith
      %span.pull-right.text-muted
        %em Yesterday
    %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
%li.divider
%li
  %a{:href => "#"}
    %div
      %strong John Smith
      %span.pull-right.text-muted
        %em Yesterday
    %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
%li.divider
%li
  %a{:href => "#"}
    %div
      %strong John Smith
      %span.pull-right.text-muted
        %em Yesterday
    %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
%li.divider
%li
  %a.text-center{:href => "#"}
    %strong Read All Messages
    %i.fa.fa-angle-right
/ /.dropdown-messages

app/views/home/_dropdown_tasks.haml
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 1
        %span.pull-right.text-muted 40% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
          %span.sr-only 40% Complete (success)
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 2
        %span.pull-right.text-muted 20% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
          %span.sr-only 20% Complete
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 3
        %span.pull-right.text-muted 60% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
          %span.sr-only 60% Complete (warning)
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 4
        %span.pull-right.text-muted 80% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
          %span.sr-only 80% Complete (danger)
%li.divider
%li
  %a.text-center{:href => "#"}
    %strong See All Tasks
    %i.fa.fa-angle-right
/ /.dropdown-tasks

app/views/home/_side_menu.haml
%li
  %a{:href => "index.html"}
    %i.fa.fa-dashboard.fa-fw
    Dashboard
%li
  %a{:href => "#"}
    %i.fa.fa-bar-chart-o.fa-fw
    Charts
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "flot.html"} Flot Charts
    %li
      %a{:href => "morris.html"} Morris.js Charts
  / /.nav-second-level
%li
  %a{:href => "tables.html"}
    %i.fa.fa-table.fa-fw
    Tables
%li
  %a{:href => "forms.html"}
    %i.fa.fa-edit.fa-fw
    Forms
%li
  %a{:href => "#"}
    %i.fa.fa-wrench.fa-fw
    UI Elements
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "panels_wells.html"} Panels and Wells
    %li
      %a{:href => "buttons.html"} Buttons
    %li
      %a{:href => "notifications.html"} Notifications
    %li
      %a{:href => "typography.html"} Typography
    %li
      %a{:href => "grid.html"} Grid
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-sitemap.fa-fw
    Multi-Level Dropdown
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"}
        Third Level
        %span.fa.arrow
      %ul.nav.nav-third-level
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
      / /.nav-third-level
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-files-o.fa-fw
    Sample Pages
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "blank.html"} Blank Page
    %li
      %a{:href => "login.html"} Login Page
  / /.nav-second-level
/ /#side-menu

app/views/home/blank.haml
.row
  .col-lg-12
    %h1.page-header Blank

app/views/home/buttons.haml
.row
  .col-lg-12
    %h1.page-header Buttons
  / /.col-lg-12
/ /.row
.row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Default Buttons
      / /.panel-heading
      .panel-body
        %h4 Normal Buttons
        %p
          %button.btn.btn-default{:type => "button"} Default
          %button.btn.btn-primary{:type => "button"} Primary
          %button.btn.btn-success{:type => "button"} Success
          %button.btn.btn-info{:type => "button"} Info
          %button.btn.btn-warning{:type => "button"} Warning
          %button.btn.btn-danger{:type => "button"} Danger
          %button.btn.btn-link{:type => "button"} Link
        %br
          %h4 Disabled Buttons
          %p
            %button.btn.btn-default.disabled{:type => "button"} Default
            %button.btn.btn-primary.disabled{:type => "button"} Primary
            %button.btn.btn-success.disabled{:type => "button"} Success
            %button.btn.btn-info.disabled{:type => "button"} Info
            %button.btn.btn-warning.disabled{:type => "button"} Warning
            %button.btn.btn-danger.disabled{:type => "button"} Danger
            %button.btn.btn-link.disabled{:type => "button"} Link
          %br
            %h4 Button Sizes
            %p
              %button.btn.btn-primary.btn-lg{:type => "button"} Large button
              %button.btn.btn-primary{:type => "button"} Default button
              %button.btn.btn-primary.btn-sm{:type => "button"} Small button
              %button.btn.btn-primary.btn-xs{:type => "button"} Mini button
              %br
                %br
                  %button.btn.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
    / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Circle Icon Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Normal Circle Buttons
        %button.btn.btn-default.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-primary.btn-circle{:type => "button"}
          %i.fa.fa-list
        %button.btn.btn-success.btn-circle{:type => "button"}
          %i.fa.fa-link
        %button.btn.btn-info.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-warning.btn-circle{:type => "button"}
          %i.fa.fa-times
        %button.btn.btn-danger.btn-circle{:type => "button"}
          %i.fa.fa-heart
        %br
          %br
            %h4 Large Circle Buttons
            %button.btn.btn-default.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-check
            %button.btn.btn-primary.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-list
            %button.btn.btn-success.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-link
            %button.btn.btn-info.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-check
            %button.btn.btn-warning.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-times
            %button.btn.btn-danger.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-heart
            %br
              %br
                %h4 Extra Large Circle Buttons
                %button.btn.btn-default.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-check
                %button.btn.btn-primary.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-list
                %button.btn.btn-success.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-link
                %button.btn.btn-info.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-check
                %button.btn.btn-warning.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-times
                %button.btn.btn-danger.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-heart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Outline Buttons with Smooth Transition
      / /.panel-heading
      .panel-body
        %h4 Outline Buttons
        %p
          %button.btn.btn-outline.btn-default{:type => "button"} Default
          %button.btn.btn-outline.btn-primary{:type => "button"} Primary
          %button.btn.btn-outline.btn-success{:type => "button"} Success
          %button.btn.btn-outline.btn-info{:type => "button"} Info
          %button.btn.btn-outline.btn-warning{:type => "button"} Warning
          %button.btn.btn-outline.btn-danger{:type => "button"} Danger
          %button.btn.btn-outline.btn-link{:type => "button"} Link
        %br
          %h4 Outline Button Sizes
          %p
            %button.btn.btn-outline.btn-primary.btn-lg{:type => "button"} Large button
            %button.btn.btn-outline.btn-primary{:type => "button"} Default button
            %button.btn.btn-outline.btn-primary.btn-sm{:type => "button"} Small button
            %button.btn.btn-outline.btn-primary.btn-xs{:type => "button"} Mini button
            %br
              %br
                %button.btn.btn-outline.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
    / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Social Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Social Buttons
        %a.btn.btn-block.btn-social.btn-bitbucket
          %i.fa.fa-bitbucket
          Sign in with Bitbucket
        %a.btn.btn-block.btn-social.btn-dropbox
          %i.fa.fa-dropbox
          Sign in with Dropbox
        %a.btn.btn-block.btn-social.btn-facebook
          %i.fa.fa-facebook
          Sign in with Facebook
        %a.btn.btn-block.btn-social.btn-flickr
          %i.fa.fa-flickr
          Sign in with Flickr
        %a.btn.btn-block.btn-social.btn-github
          %i.fa.fa-github
          Sign in with GitHub
        %a.btn.btn-block.btn-social.btn-google-plus
          %i.fa.fa-google-plus
          Sign in with Google
        %a.btn.btn-block.btn-social.btn-instagram
          %i.fa.fa-instagram
          Sign in with Instagram
        %a.btn.btn-block.btn-social.btn-linkedin
          %i.fa.fa-linkedin
          Sign in with LinkedIn
        %a.btn.btn-block.btn-social.btn-pinterest
          %i.fa.fa-pinterest
          Sign in with Pinterest
        %a.btn.btn-block.btn-social.btn-tumblr
          %i.fa.fa-tumblr
          Sign in with Tumblr
        %a.btn.btn-block.btn-social.btn-twitter
          %i.fa.fa-twitter
          Sign in with Twitter
        %a.btn.btn-block.btn-social.btn-vk
          %i.fa.fa-vk
          Sign in with VK
        %hr
          .text-center
            %a.btn.btn-social-icon.btn-bitbucket
              %i.fa.fa-bitbucket
            %a.btn.btn-social-icon.btn-dropbox
              %i.fa.fa-dropbox
            %a.btn.btn-social-icon.btn-facebook
              %i.fa.fa-facebook
            %a.btn.btn-social-icon.btn-flickr
              %i.fa.fa-flickr
            %a.btn.btn-social-icon.btn-github
              %i.fa.fa-github
            %a.btn.btn-social-icon.btn-google-plus
              %i.fa.fa-google-plus
            %a.btn.btn-social-icon.btn-instagram
              %i.fa.fa-instagram
            %a.btn.btn-social-icon.btn-linkedin
              %i.fa.fa-linkedin
            %a.btn.btn-social-icon.btn-pinterest
              %i.fa.fa-pinterest
            %a.btn.btn-social-icon.btn-tumblr
              %i.fa.fa-tumblr
            %a.btn.btn-social-icon.btn-twitter
              %i.fa.fa-twitter
            %a.btn.btn-social-icon.btn-vk
              %i.fa.fa-vk
      / /.panel-body
    / /.panel
  / /.col-lg-6
/ /.row

app/views/home/login.haml
.container
  .row
    .col-md-4.col-md-offset-4
      .login-panel.panel.panel-default
        .panel-heading
          %h3.panel-title Please Sign In
        .panel-body
          %form{:role => "form"}
            %fieldset
              .form-group
                %input.form-control{:autofocus => "", :name => "email", :placeholder => "E-mail", :type => "email"}
              .form-group
                %input.form-control{:name => "password", :placeholder => "Password", :type => "password", :value => ""}
              .checkbox
                %label
                  %input{:name => "remember", :type => "checkbox", :value => "Remember Me"}
                    Remember Me
              / Change this to a button or input when using this as a form
              %a.btn.btn-lg.btn-success.btn-block{:href => "index.haml"} Login

app/views/settings/_form.html.haml
= form_for @setting do |f|
  - if @setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :group
    = f.text_field :group
  .field
    = f.label :key
    = f.text_field :key
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :note
    = f.text_area :note
  .actions
    = f.submit 'Save'

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 Listing settings

%table
  %tr
    %th Group
    %th Key
    %th Value
    %th Note
    %th
    %th
    %th

  - @settings.each do |setting|
    %tr
      %td= setting.group
      %td= setting.key
      %td= setting.value
      %td= setting.note
      %td= link_to 'Show', setting
      %td= link_to 'Edit', edit_setting_path(setting)
      %td= link_to 'Destroy', setting, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice

%p
  %b Group:
  = @setting.group
%p
  %b Key:
  = @setting.key
%p
  %b Value:
  = @setting.value
%p
  %b Note:
  = @setting.note

= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Back', settings_path